// ============================================================================
// cache_service.h — gRPC Service Handler (The Network Interface to the Cache)
// ============================================================================
//
// WHAT IS THIS FILE?
//   This header defines CacheServiceImpl, a C++ class that "implements" the
//   CacheService gRPC service defined in cache.proto.
//
// HOW gRPC WORKS END-TO-END:
//   1. protoc generates a base class: CacheService::Service (in cache.grpc.pb.h).
//      This base class has virtual stubs for every RPC you declared in the .proto.
//   2. We subclass it (CacheServiceImpl : public CacheService::Service) and
//      override each virtual method with REAL logic.
//   3. The gRPC ServerBuilder registers our CacheServiceImpl instance.
//   4. The gRPC runtime spawns a thread pool. When a client sends a request,
//      one of those threads calls our override with the deserialized request object.
//   5. We do our work (call the cache, increment metrics), fill the response object,
//      and return grpc::Status::OK.
//   6. The gRPC runtime serializes the response back to the client over the network.
//
// WHY IS THIS A SEPARATE CLASS FROM CacheStore?
//   Separation of Concerns — CacheStore handles data storage and concurrency.
//   CacheServiceImpl handles network protocol translation and observability.
//   This makes unit testing simpler: you can test CacheStore without a network,
//   and test CacheServiceImpl with a mock CacheStore.
//
// DEPENDENCY INJECTION PATTERN:
//   Both CacheStore and MetricsExporter are passed IN to the constructor
//   as shared_ptrs. This is Dependency Injection — the class does NOT own
//   or construct these objects. This enables:
//     - Testing: pass mock objects for isolated unit tests.
//     - Sharing: the same CacheStore can be accessed by multiple services.
//     - Lifecycle management: shared_ptr ensures proper cleanup.
//
// ============================================================================

#pragma once

#include <grpcpp/grpcpp.h>
#include <memory>

// These headers are generated by protoc from cache.proto.
// They contain the C++ classes for SetRequest, GetRequest, etc., and the
// base class CacheService::Service that we need to override.
#include "cache.grpc.pb.h"

#include "cache/cache_store.h"
#include "metrics/prometheus_exporter.h"

namespace distcache {

class CacheServiceImpl final : public CacheService::Service {
    // `final`: This class cannot be subclassed further. Tells the compiler
    // it can de-virtualize method calls for a small performance gain.

public:
    // Constructor uses Dependency Injection — receives pre-built shared_ptrs.
    // Using shared_ptr (not raw pointer or unique_ptr) so both this class and
    // the main.cpp caller share ownership. The objects are alive as long as
    // at least one shared_ptr to them exists.
    explicit CacheServiceImpl(std::shared_ptr<CacheStore> store,
                               std::shared_ptr<MetricsExporter> metrics);

    // -------------------------------------------------------------------------
    // gRPC RPC Handlers
    // -------------------------------------------------------------------------
    // Each method signature is dictated by the generated base class.
    // Parameters:
    //   - ServerContext*: gRPC metadata (client address, deadlines, trailers).
    //                     We don't use it directly but it's required by the interface.
    //   - const XxxRequest*: The deserialized request proto message.
    //   - XxxResponse*: The response message to fill in before returning.
    // Return Value:
    //   grpc::Status::OK → success. The gRPC runtime sends the response.
    //   grpc::Status(grpc::INVALID_ARGUMENT, "msg") → error. Client receives error code.

    grpc::Status Set(grpc::ServerContext* context,
                     const SetRequest* request,
                     SetResponse* response) override;

    grpc::Status Get(grpc::ServerContext* context,
                     const GetRequest* request,
                     GetResponse* response) override;

    grpc::Status Delete(grpc::ServerContext* context,
                        const DeleteRequest* request,
                        DeleteResponse* response) override;

    grpc::Status Exists(grpc::ServerContext* context,
                        const ExistsRequest* request,
                        ExistsResponse* response) override;

    grpc::Status Stats(grpc::ServerContext* context,
                       const StatsRequest* request,
                       StatsResponse* response) override;

private:
    // shared_ptr members — reference-counted smart pointers.
    // Multiple threads may call these handlers concurrently.
    // CacheStore is internally thread-safe (sharded with mutexes).
    // MetricsExporter is internally thread-safe (atomic counters).
    // So there is no additional locking needed here.
    std::shared_ptr<CacheStore> store_;
    std::shared_ptr<MetricsExporter> metrics_;
};

}  // namespace distcache
